// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '########################################',
    appId: '########################################',
    messagingSenderId: '124622173320',
    projectId: 'tradeiq-3a498',
    authDomain: 'tradeiq-3a498.firebaseapp.com',
    storageBucket: 'tradeiq-3a498.appspot.com',
    measurementId: 'G-JF6PZ44HE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '########################################',
    appId: '########################################',
    messagingSenderId: '124622173320',
    projectId: 'tradeiq-3a498',
    storageBucket: 'tradeiq-3a498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '########################################',
    appId: '########################################',
    messagingSenderId: '124622173320',
    projectId: 'tradeiq-3a498',
    storageBucket: 'tradeiq-3a498.appspot.com',
    iosClientId: '124622173320-f771vqoke0v73ii1qfd1imdcsfm70i13.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradeiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '########################################',
    appId: '########################################',
    messagingSenderId: '124622173320',
    projectId: 'tradeiq-3a498',
    storageBucket: 'tradeiq-3a498.appspot.com',
    iosClientId: '124622173320-2hprp6otbssh9i0oi7ngung0p0v2u8vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradeiq.RunnerTests',
  );
}
